#docker stack deploy --compose-file docker-compose2.yml ABWBS01

##DEPLOY
## docker stack deploy --compose-file docker-compose.yml ABWBS



version: "3.7"

services:
  ############### PORTAINER ###########
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    #networks:
    #  - pagent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          cpus: '0.50'
          memory: 100M


  portainer:
    image: portainer/portainer:latest
    command: 
      -H tcp://tasks.agent:9001 --tlsskipverify
      --ssl
      --sslcert /certs/portainer.crt
      --sslkey /certs/portainer.key 
      #--admin-password=${CLIENT_SECRET}
    ports:
      - "9444:9000" ## (NOT WORKING BEYOND FROM FIREWALL- WORK ONLY INSIDE)
    #volumes:
    #  - /var/lib/docker/volumes/ABPortainer/_data/data:/data
    #  - /var/lib/docker/volumes/ABPortainer/_data/certs:/certs
    volumes:
      - type: volume
        source: volume01
        target: /data
        volume:
          nocopy: true
      - /var/lib/docker/volumes/ABPortainer/_data/certs:/certs
    #  - type: volume
    #    source: volume01
    #    target: /certs
    #    volume:
    #      nocopy: true
    #  - /mnt/ABWBS-Portainer:/data
    #  - /mnt/ABWBS-Portainer/certs:/certs

    #networks:
    #  - pagent_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure ##any
        delay: 10s
        max_attempts: 10
      #placement:
        #constraints: [node.role == manager] 
        #constraints: [node.hostname == USRV4] 
      resources:
        limits:
          cpus: '0.50'
          memory: 100M

  #######################################      
volumes:
  volume01:
    name: ABPortainer
 

#networks:
#  pagent_network:
#    driver: overlay
#    attachable: true  ##FOR ATTACH CONTAINERS ALLOW 
 


